// AUTO-GENERATED by scripts/gen-credentials.mjs from workspace/sidecars/**. Do not edit by hand.
export interface CredentialUsage { sidecar: string; usage: string; }
export interface CredentialField { key: string; label: string; usages: CredentialUsage[]; }
export interface CredentialGroup { name: string; description: string; fields: CredentialField[]; }

export const CREDENTIAL_GROUPS: CredentialGroup[] = [
  {
    "name": "GitHub",
    "description": "Authenticates git operations in the workspace (private repos, higher rate limits).",
    "fields": [
      {
        "key": "ghToken",
        "label": "GitHub token",
        "usages": [
          {
            "sidecar": "workspace",
            "usage": "clones private rancher/dashboard PRs & repos"
          }
        ]
      }
    ]
  },
  {
    "name": "Figma",
    "description": "Access token for the Figma MCP server, so agents can read designs.",
    "fields": [
      {
        "key": "apiKey",
        "label": "Figma API key",
        "usages": [
          {
            "sidecar": "figma",
            "usage": "Figma MCP server authentication"
          }
        ]
      }
    ]
  },
  {
    "name": "AWS",
    "description": "Credentials for provisioning AWS clusters (EC2 nodes / EKS) in Rancher.",
    "fields": [
      {
        "key": "awsAccessKey",
        "label": "AWS access key",
        "usages": [
          {
            "sidecar": "rancher",
            "usage": "inserted into Rancher as a cloud credential at start"
          }
        ]
      },
      {
        "key": "awsSecretKey",
        "label": "AWS secret key",
        "usages": [
          {
            "sidecar": "rancher",
            "usage": "inserted into Rancher as a cloud credential at start"
          }
        ]
      }
    ]
  },
  {
    "name": "Azure",
    "description": "Service-principal credentials for provisioning AKS clusters in Rancher.",
    "fields": [
      {
        "key": "azureClientId",
        "label": "Azure client ID",
        "usages": [
          {
            "sidecar": "rancher",
            "usage": "cloud credential for provisioning AKS clusters"
          }
        ]
      },
      {
        "key": "azureClientSecret",
        "label": "Azure client secret",
        "usages": [
          {
            "sidecar": "rancher",
            "usage": "cloud credential for provisioning AKS clusters"
          }
        ]
      },
      {
        "key": "azureSubscriptionId",
        "label": "Azure subscription ID",
        "usages": [
          {
            "sidecar": "rancher",
            "usage": "cloud credential for provisioning AKS clusters"
          }
        ]
      },
      {
        "key": "azureTenantId",
        "label": "Azure tenant ID",
        "usages": [
          {
            "sidecar": "rancher",
            "usage": "cloud credential for provisioning AKS clusters"
          }
        ]
      }
    ]
  },
  {
    "name": "GCP",
    "description": "Service-account key for provisioning GKE clusters in Rancher.",
    "fields": [
      {
        "key": "gcpServiceAccountKey",
        "label": "GCP service account key",
        "usages": [
          {
            "sidecar": "rancher",
            "usage": "cloud credential for provisioning GKE clusters"
          }
        ]
      }
    ]
  }
];

// Flat list of every credential key (for the "N/total" Keys column).
export const CREDENTIAL_KEYS: string[] = ["ghToken","apiKey","awsAccessKey","awsSecretKey","azureClientId","azureClientSecret","azureSubscriptionId","azureTenantId","gcpServiceAccountKey"];
